#!/bin/sh

xcape -t 300 &

~/config/scripts/home_setup.sh

pkill sxhkd
sxhkd &

pkill polybar
polybar main &

bspc monitor -d I II III IV V

bspc config border_width 3
bspc config window_gap 5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle false
bspc config single_monocle true

bspc config focus_follows_pointer true

bspc config split_ratio 0.50

bspc config focused_border_color "#FF0000"

# bspc rule -a scratchpad sticky=on state=floating hidden=on
# alacritty -c scratchpad -e ~/bin/scratch &

# id=$(cat /tmp/scratchid);\
# bspc node $id --flag hidden;bspc node -f $id
