#!/usr/bin/env bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width                3
bspc config window_gap                  5
bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config focused_border_color        '#FF0000'
bspc config focus_follows_pointer       true
bspc config initial_polarity            'second_child'
bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true

bspc rule -a Zathura state=tiled

reload-settings &
