#!/usr/bin/env bash

reload-settings &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            3
bspc config window_gap              5
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focused_border_color    '#FF0000'
bspc config focus_follows_pointer   true
bspc config initial_polarity        'second_child'
