code --install-extension asabil.meson
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension faustinoaq.lex-flex-yacc-bison
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.auto-rename-tag
code --install-extension James-Yu.latex-workshop
code --install-extension jithurjacob.nbpreviewer
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension lextudio.restructuredtext
code --install-extension mikestead.dotenv
code --install-extension mitaki28.vscode-clang
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension PeterJausovec.vscode-docker
code --install-extension platformio.platformio-ide
code --install-extension redhat.java
code --install-extension rust-lang.rust
code --install-extension serayuzgur.crates
code --install-extension sidneys1.gitconfig
code --install-extension sjhuangx.vscode-scheme
code --install-extension twxs.cmake
code --install-extension vscjava.vscode-java-debug
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension xabikos.ReactSnippets
code --install-extension ybaumes.highlight-trailing-white-spaces
