code --install-extension alanz.vscode-hie-server
code --install-extension asabil.meson
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.path-intellisense
code --install-extension darkriszty.markdown-table-prettify
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension faustinoaq.lex-flex-yacc-bison
code --install-extension formulahendry.auto-rename-tag
code --install-extension James-Yu.latex-workshop
code --install-extension JamesBirtles.svelte-vscode
code --install-extension jithurjacob.nbpreviewer
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension justusadam.language-haskell
code --install-extension matklad.rust-analyzer
code --install-extension mikestead.dotenv
code --install-extension mitaki28.vscode-clang
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension serayuzgur.crates
code --install-extension sidneys1.gitconfig
code --install-extension sjhuangx.vscode-scheme
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension twxs.cmake
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension ybaumes.highlight-trailing-white-spaces
code --install-extension yzhang.markdown-all-in-one
