#!/usr/bin/env bash

sink=$(pacmd list-sinks | grep '*' | awk '{print $3}')

print_volume() {
    muted=$(pamixer --sink $sink --get-mute)

    if [ "$muted" = true ]; then
        echo " MUTE"
    else
        volume=$(pamixer --sink $sink --get-volume)

        if [ "$volume" -lt 50 ]; then
            echo " $volume%"
        else
            echo " $volume%"
        fi
    fi
}

monitor() {
    print_volume

    pactl subscribe | while read -r event; do
        if echo "$event" | grep -q "#$sink"; then
            sink=$(pacmd list-sinks | grep '*' | awk '{print $3}')
            print_volume
        fi
    done
}

monitor
