#!/usr/bin/bash

W='#d3d3d3DD'
B='#000000FF'
R='#FF0000FF'

i3lock                      \
    -e                      \
\
    --blur=sigma            \
\
    -k                      \
    -u                      \
\
    --timestr="%H:%M"       \
    --timesize=75           \
    --timecolor=$W          \
\
    --datestr="%A, %B %d"   \
    --datesize=25           \
    --datepos="tx:ty+40"    \
    --datecolor=$W          \
\
    --bordercolor=$B        \
